project_id = "waniryugscczamjzhhvy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.xendit-webhook]
verify_jwt = false

[functions.check-expired-subscriptions]
verify_jwt = false