// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waniryugscczamjzhhvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhbmlyeXVnc2NjemFtanpoaHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxODM2ODIsImV4cCI6MjA2OTc1OTY4Mn0.VuzJ7eF8VX1z6wXSAQu1gQYIvhJ8ZGc4eF_4OkIcg2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});